-- Ejecutar en el SQL Editor de Supabase después de 016_catalog_breeds.sql
-- Catálogo de RAZAS por especie — lista entregada por el cliente
-- Fuente: Excel "Lista de Especies con Raza" (7 hojas, columna A = especie, B = raza)
-- Generado por tools/scripts/build_breeds_seed.py — no editar a mano

INSERT INTO catalog_breeds (breed_key, name, species) VALUES
-- ── AVE ────────────────────────────────────────────────────────────────────
('agapornis',                        'Agapornis', 'Ave'),
('ave',                              'Ave', 'Ave'),
('cacatua_paraguas',                 'Cacatua Paraguas', 'Ave'),
('cacatua_de_molucas',               'Cacatua de Molucas', 'Ave'),
('cacatua',                          'Cacatúa', 'Ave'),
('canario',                          'Canario', 'Ave'),
('codorniz_japonesa',                'Codorniz Japonesa', 'Ave'),
('conure',                           'Conure', 'Ave'),
('gallina',                          'Gallina', 'Ave'),
('ganso_toulouse',                   'Ganso Toulouse', 'Ave'),
('guacamaya',                        'Guacamaya', 'Ave'),
('guacamaya_roja',                   'Guacamaya Roja', 'Ave'),
('isa_brown',                        'Isa Brown', 'Ave'),
('leghorn',                          'Leghorn', 'Ave'),
('loro_amazona',                     'Loro Amazona', 'Ave'),
('loro_o_electus_parrot',            'Loro o Electus Parrot', 'Ave'),
('ninfa',                            'Ninfa', 'Ave'),
('pato_pekin',                       'Pato Pekín', 'Ave'),
('periquito_australiano',            'Periquito Australiano', 'Ave'),
('plymouth_rock',                    'Plymouth Rock', 'Ave'),
('rhode_island_red',                 'Rhode Island Red', 'Ave'),

-- ── AXOLOTE ────────────────────────────────────────────────────────────────
('axolote',                          'Axolote', 'Axolote'),

-- ── BOVINO ─────────────────────────────────────────────────────────────────
('angus',                            'Angus', 'Bovino'),
('bon',                              'BON', 'Bovino'),
('brahman',                          'Brahman', 'Bovino'),
('cebu',                             'Cebu', 'Bovino'),
('charolais',                        'Charolais', 'Bovino'),
('criollo',                          'Criollo', 'Bovino'),
('ganado_vacuno',                    'Ganado Vacuno', 'Bovino'),
('girolando',                        'Girolando', 'Bovino'),
('guzera',                           'Guzerá', 'Bovino'),
('gyr',                              'Gyr', 'Bovino'),
('hereford',                         'Hereford', 'Bovino'),
('holstein',                         'Holstein', 'Bovino'),
('jersey',                           'Jersey', 'Bovino'),
('limousin',                         'Limousin', 'Bovino'),
('normado',                          'Normado', 'Bovino'),
('romosinuano',                      'Romosinuano', 'Bovino'),
('simmental',                        'Simmental', 'Bovino'),
('vaca_lechera',                     'Vaca Lechera', 'Bovino'),

-- ── CANINO ─────────────────────────────────────────────────────────────────
('affenpinscher',                    'Affenpinscher', 'Canino'),
('afgano',                           'Afgano', 'Canino'),
('airedale_terrier',                 'Airedale terrier', 'Canino'),
('akbash',                           'Akbash', 'Canino'),
('akita',                            'Akita', 'Canino'),
('akita_americano',                  'Akita americano', 'Canino'),
('alaska_malamute',                  'Alaska malamute', 'Canino'),
('american_bully',                   'American bully', 'Canino'),
('american_staffordshire',           'American staffordshire', 'Canino'),
('american_staffordshire_terrier',   'American staffordshire terrier', 'Canino'),
('australian_terrier',               'Australian terrier', 'Canino'),
('basenji',                          'Basenji', 'Canino'),
('basset_hound',                     'Basset Hound', 'Canino'),
('beagle',                           'Beagle', 'Canino'),
('beagle_collie',                    'Beagle collie', 'Canino'),
('bernes_de_la_montana',             'Bernes de la montaña', 'Canino'),
('bernes_suizo',                     'Bernes suizo', 'Canino'),
('bichon',                           'Bichon', 'Canino'),
('bichon_frise',                     'Bichon frise', 'Canino'),
('bichon_habanero',                  'Bichon habanero', 'Canino'),
('bichon_maltes',                    'Bichon maltes', 'Canino'),
('biewer_terrier',                   'Biewer terrier', 'Canino'),
('border_collie',                    'Border Collie', 'Canino'),
('boston_terrier',                   'Boston Terrier', 'Canino'),
('boyero_de_berna',                  'Boyero de berna', 'Canino'),
('boyero_suizo',                     'Boyero suizo', 'Canino'),
('braco_aleman',                     'Braco alemán', 'Canino'),
('bull_terrier',                     'Bull Terrier', 'Canino'),
('bulldog',                          'Bulldog', 'Canino'),
('bulldog_frances',                  'Bulldog Francés', 'Canino'),
('bulldog_ingles',                   'Bulldog Inglés', 'Canino'),
('bullmastiff',                      'Bullmastiff', 'Canino'),
('boxer',                            'Bóxer', 'Canino'),
('cane_corso',                       'Cane Corso', 'Canino'),
('caniche',                          'Caniche', 'Canino'),
('cavalier',                         'Cavalier', 'Canino'),
('cavapoo',                          'Cavapoo', 'Canino'),
('chihuahua',                        'Chihuahua', 'Canino'),
('chow_chow',                        'Chow Chow', 'Canino'),
('clumber_spaniel',                  'Clumber spaniel', 'Canino'),
('cocker',                           'Cocker', 'Canino'),
('cocker_spaniel',                   'Cocker Spaniel', 'Canino'),
('collie',                           'Collie', 'Canino'),
('corgi',                            'Corgi', 'Canino'),
('corgi_gales',                      'Corgi gales', 'Canino'),
('cotton',                           'Cotton', 'Canino'),
('crestado_chino',                   'Crestado chino', 'Canino'),
('dachshund',                        'Dachshund', 'Canino'),
('doberman',                         'Doberman', 'Canino'),
('dogo',                             'Dogo', 'Canino'),
('dogo_argentino',                   'Dogo Argentino', 'Canino'),
('dogo_de_burdeos',                  'Dogo de Burdeos', 'Canino'),
('dalmata',                          'Dálmata', 'Canino'),
('fila_brasilero',                   'Fila Brasilero', 'Canino'),
('flat_coated_retriever',            'Flat Coated Retriever', 'Canino'),
('fox_terrier',                      'Fox Terrier', 'Canino'),
('french_poodle',                    'French Poodle', 'Canino'),
('galgo',                            'Galgo', 'Canino'),
('galgo_afgano',                     'Galgo Afgano', 'Canino'),
('galgo_italiano',                   'Galgo Italiano', 'Canino'),
('ganadero_australiano',             'Ganadero Australiano', 'Canino'),
('golden_retriever',                 'Golden Retriever', 'Canino'),
('goldendoodle',                     'Goldendoodle', 'Canino'),
('gran_danes',                       'Gran Danés', 'Canino'),
('gran_azul_de_gascuna',             'Gran azul de gascuña', 'Canino'),
('griffon_de_bruselas',              'Griffon de Bruselas', 'Canino'),
('husky_siberiano',                  'Husky Siberiano', 'Canino'),
('jack_russell_terrier',             'Jack Russell Terrier', 'Canino'),
('komondor',                         'Komondor', 'Canino'),
('labmaraner',                       'Labmaraner', 'Canino'),
('labradoodle',                      'Labradoodle', 'Canino'),
('labrador',                         'Labrador', 'Canino'),
('labrador_retriever',               'Labrador Retriever', 'Canino'),
('lhasa_apso',                       'Lhasa apso', 'Canino'),
('lobero_irlandes',                  'Lobero irlandés', 'Canino'),
('maltes',                           'Maltes', 'Canino'),
('manchester_terrier',               'Manchester terrier', 'Canino'),
('mastin',                           'Mastin', 'Canino'),
('mastin_italiano',                  'Mastin Italiano', 'Canino'),
('mastin_napolitano',                'Mastin Napolitano', 'Canino'),
('mastin_tibetano',                  'Mastin Tibetano', 'Canino'),
('mestizo',                          'Mestizo', 'Canino'),
('mini_toy',                         'Mini Toy', 'Canino'),
('papillon',                         'Papillon', 'Canino'),
('parson_russell_terrier',           'Parson Russell Terrier', 'Canino'),
('pastor',                           'Pastor', 'Canino'),
('pastor_aleman',                    'Pastor Alemán', 'Canino'),
('pastor_alsaciano',                 'Pastor Alsaciano', 'Canino'),
('pastor_australiano',               'Pastor Australiano', 'Canino'),
('pastor_belga',                     'Pastor Belga', 'Canino'),
('pastor_belga_malinois',            'Pastor Belga Malinois', 'Canino'),
('pastor_catalan',                   'Pastor Catalan', 'Canino'),
('pastor_collie',                    'Pastor Collie', 'Canino'),
('pastor_ganadero',                  'Pastor Ganadero', 'Canino'),
('pastor_mallinois',                 'Pastor Mallinois', 'Canino'),
('pastor_ovejero',                   'Pastor Ovejero', 'Canino'),
('pastor_shetland',                  'Pastor Shetland', 'Canino'),
('pastor_suizo',                     'Pastor Suizo', 'Canino'),
('pastor_de_anatolia',               'Pastor de Anatolia', 'Canino'),
('pastor_de_brie',                   'Pastor de Brie', 'Canino'),
('pastor_de_los_pirineos',           'Pastor de los Pirineos', 'Canino'),
('pastor_holandes',                  'Pastor holandés', 'Canino'),
('pekines',                          'Pekines', 'Canino'),
('perro_de_agua_espanol',            'Perro de Agua Español', 'Canino'),
('perro_de_montana_de_los_pirineos', 'Perro de Montaña de los Pirineos', 'Canino'),
('pinscher',                         'Pinscher', 'Canino'),
('pinscher_miniatura',               'Pinscher Miniatura', 'Canino'),
('pit_bull_terrier',                 'Pit Bull Terrier', 'Canino'),
('pitbull',                          'Pitbull', 'Canino'),
('pointer',                          'Pointer', 'Canino'),
('pointer_aleman',                   'Pointer Alemán', 'Canino'),
('pointer_ingles',                   'Pointer Ingles', 'Canino'),
('pomerania',                        'Pomerania', 'Canino'),
('pomsky',                           'Pomsky', 'Canino'),
('pomsteyssa',                       'Pomsteyssa', 'Canino'),
('poodle',                           'Poodle', 'Canino'),
('portugues_de_agua',                'Portugués de agua', 'Canino'),
('ptibull_terrier',                  'Ptibull terrier', 'Canino'),
('pug',                              'Pug', 'Canino'),
('ratonero_de_praga',                'Ratonero de praga', 'Canino'),
('rhodesian_ridgeback',              'Rhodesian Ridgeback', 'Canino'),
('rodhesian',                        'Rodhesian', 'Canino'),
('rottweiler',                       'Rottweiler', 'Canino'),
('sabueso_colombiano',               'Sabueso colombiano', 'Canino'),
('sabueso_espanol',                  'Sabueso español', 'Canino'),
('salchicha',                        'Salchicha', 'Canino'),
('salchicha_mini',                   'Salchicha mini', 'Canino'),
('samoyedo',                         'Samoyedo', 'Canino'),
('san_bernardo',                     'San Bernardo', 'Canino'),
('schnauzer',                        'Schnauzer', 'Canino'),
('schnauzer_miniatura',              'Schnauzer Miniatura', 'Canino'),
('scottish_terrier',                 'Scottish terrier', 'Canino'),
('setter_irlandes',                  'Setter irlandes', 'Canino'),
('shar_pei',                         'Shar Pei', 'Canino'),
('shetland_sheepdog',                'Shetland Sheepdog', 'Canino'),
('shiba_inu',                        'Shiba inu', 'Canino'),
('shih_tzu',                         'Shih Tzu', 'Canino'),
('siberiano',                        'Siberiano', 'Canino'),
('spaniel',                          'Spaniel', 'Canino'),
('spitz_japones',                    'Spitz japonés', 'Canino'),
('springer_spaniel',                 'Springer spaniel', 'Canino'),
('staffordshire_bull_terrier',       'Staffordshire Bull Terrier', 'Canino'),
('staffordshire_terrier_americano',  'Staffordshire Terrier Americano', 'Canino'),
('tacita_de_te',                     'Tacita de te', 'Canino'),
('teckel',                           'Teckel', 'Canino'),
('terranova',                        'Terranova', 'Canino'),
('terrier',                          'Terrier', 'Canino'),
('terrier_escoces',                  'Terrier escocés', 'Canino'),
('terrier_irlandes',                 'Terrier irlandes', 'Canino'),
('terry_moster',                     'Terry moster', 'Canino'),
('unica',                            'Unica', 'Canino'),
('weimaraner',                       'Weimaraner', 'Canino'),
('west_highland_white_terrier',      'West highland white terrier', 'Canino'),
('westie',                           'Westie', 'Canino'),
('xoloitzcuintle',                   'Xoloitzcuintle', 'Canino'),
('yorkie',                           'Yorkie', 'Canino'),
('yorkshire_terrier',                'Yorkshire Terrier', 'Canino'),

-- ── CAPRINO ────────────────────────────────────────────────────────────────
('alpina',                           'Alpina', 'Caprino'),
('anglo_nubian',                     'Anglo Nubian', 'Caprino'),
('boer',                             'Boer', 'Caprino'),
('lamancha',                         'LaMancha', 'Caprino'),
('saanen',                           'Saanen', 'Caprino'),
('toggenburg',                       'Toggenburg', 'Caprino'),

-- ── CHINCHILLA ─────────────────────────────────────────────────────────────
('chinchilla',                       'Chinchilla', 'Chinchilla'),

-- ── CONEJO ─────────────────────────────────────────────────────────────────
('angora',                           'Angora', 'Conejo'),
('cabeza_de_leon',                   'Cabeza de León', 'Conejo'),
('californiano',                     'Californiano', 'Conejo'),
('conejo',                           'Conejo', 'Conejo'),
('gigante_de_flandes',               'Gigante de Flandes', 'Conejo'),
('holland_lop',                      'Holland Lop', 'Conejo'),
('mini_lop',                         'Mini Lop', 'Conejo'),
('nueva_zelanda',                    'Nueva Zelanda', 'Conejo'),
('rex',                              'Rex', 'Conejo'),

-- ── DEGÚ ───────────────────────────────────────────────────────────────────
('degu',                             'Degú', 'Degú'),

-- ── EQUINO ─────────────────────────────────────────────────────────────────
('andaluz',                          'Andaluz', 'Equino'),
('appaloosa',                        'Appaloosa', 'Equino'),
('criollo',                          'Criollo', 'Equino'),
('criollo_colombiano',               'Criollo Colombiano', 'Equino'),
('cruce',                            'Cruce', 'Equino'),
('cuarto_de_milla',                  'Cuarto de Milla', 'Equino'),
('frison',                           'Frisón', 'Equino'),
('haflinger',                        'Haflinger', 'Equino'),
('lusitano',                         'Lusitano', 'Equino'),
('minihorse',                        'Minihorse', 'Equino'),
('morgan',                           'Morgan', 'Equino'),
('paint_horse',                      'Paint Horse', 'Equino'),
('paso_fino_colombiano',             'Paso Fino Colombiano', 'Equino'),
('percheron_3_4_frison',             'Percheron 3/4 Frison', 'Equino'),
('percheron_argentino_psi',          'Percheron Argentino/Psi', 'Equino'),
('pura_sangre_ingles',               'Pura Sangre Inglés', 'Equino'),
('shetland_pony',                    'Shetland Pony', 'Equino'),
('yegua_de_cria_o_broodmare',        'Yegua de Cria o Broodmare', 'Equino'),
('arabe',                            'Árabe', 'Equino'),

-- ── ERIZO ──────────────────────────────────────────────────────────────────
('erizo_africano',                   'Erizo Africano', 'Erizo'),

-- ── FELINO ─────────────────────────────────────────────────────────────────
('abisinio',                         'Abisinio', 'Felino'),
('americano_shorthair',              'Americano shorthair', 'Felino'),
('angora',                           'Angora', 'Felino'),
('angora_turco',                     'Angora Turco', 'Felino'),
('apc',                              'Apc', 'Felino'),
('arlequin',                         'Arlequin', 'Felino'),
('azul_ruso',                        'Azul Ruso', 'Felino'),
('balines',                          'Balines', 'Felino'),
('bengali',                          'Bengalí', 'Felino'),
('birmano',                          'Birmano', 'Felino'),
('bobbtail',                         'Bobbtail', 'Felino'),
('bombay',                           'Bombay', 'Felino'),
('bosque_de_noruega',                'Bosque de Noruega', 'Felino'),
('british_council',                  'British Council', 'Felino'),
('british_shorthair',                'British Shorthair', 'Felino'),
('burmilla',                         'Burmilla', 'Felino'),
('burmes',                           'Burmés', 'Felino'),
('carey',                            'Carey', 'Felino'),
('chartreux',                        'Chartreux', 'Felino'),
('comun_europeo',                    'Comun Europeo', 'Felino'),
('criollo',                          'Criollo', 'Felino'),
('cruce',                            'Cruce', 'Felino'),
('devon_rex',                        'Devon Rex', 'Felino'),
('domestico_comun',                  'Domestico Común', 'Felino'),
('domestico_pelo_corto',             'Doméstico Pelo Corto', 'Felino'),
('domestico_pelo_largo',             'Doméstico Pelo Largo', 'Felino'),
('dsh',                              'Dsh', 'Felino'),
('esfinge',                          'Esfinge', 'Felino'),
('exotic_shorthair',                 'Exotic Shorthair', 'Felino'),
('exotico',                          'Exotico', 'Felino'),
('gato_somali',                      'Gato Somali', 'Felino'),
('habana',                           'Habana', 'Felino'),
('himalayo',                         'Himalayo', 'Felino'),
('khao_manee',                       'Khao Manee', 'Felino'),
('korat',                            'Korat', 'Felino'),
('maine_coon',                       'Maine Coon', 'Felino'),
('mestizo',                          'Mestizo', 'Felino'),
('mestizo_pelo_corto',               'Mestizo pelo corto', 'Felino'),
('mixto',                            'Mixto', 'Felino'),
('montes',                           'Montes', 'Felino'),
('nebelung',                         'Nebelung', 'Felino'),
('oriental',                         'Oriental', 'Felino'),
('pardo_americano',                  'Pardo americano', 'Felino'),
('pce',                              'Pce', 'Felino'),
('persa',                            'Persa', 'Felino'),
('pixie_bob',                        'Pixie bob', 'Felino'),
('ragdoll',                          'Ragdoll', 'Felino'),
('red_point',                        'Red Point', 'Felino'),
('ruso_azul',                        'Ruso Azul', 'Felino'),
('sagrado_de_birmania',              'Sagrado de Birmania', 'Felino'),
('savannah',                         'Savannah', 'Felino'),
('scottish_fold',                    'Scottish Fold', 'Felino'),
('siames',                           'Siamés', 'Felino'),
('siberiano',                        'Siberiano', 'Felino'),
('snowshoe',                         'Snowshoe', 'Felino'),
('somali',                           'Somali', 'Felino'),
('sphynx',                           'Sphynx', 'Felino'),
('srd',                              'Srd', 'Felino'),
('tabby',                            'Tabby', 'Felino'),
('unica',                            'Unica', 'Felino'),
('van_turco',                        'Van turco', 'Felino'),

-- ── HURÓN ──────────────────────────────────────────────────────────────────
('huron_domestico',                  'Hurón doméstico', 'Hurón'),

-- ── OVINO ──────────────────────────────────────────────────────────────────
('dorper',                           'Dorper', 'Ovino'),
('hampshire',                        'Hampshire', 'Ovino'),
('katahdin',                         'Katahdin', 'Ovino'),
('merino',                           'Merino', 'Ovino'),
('santa_ines',                       'Santa Inés', 'Ovino'),
('suffolk',                          'Suffolk', 'Ovino'),
('texel',                            'Texel', 'Ovino'),

-- ── PORCINO ────────────────────────────────────────────────────────────────
('cerdo',                            'Cerdo', 'Porcino'),
('duroc',                            'Duroc', 'Porcino'),
('hampshire',                        'Hampshire', 'Porcino'),
('landrace',                         'Landrace', 'Porcino'),
('large_white',                      'Large White', 'Porcino'),
('pietrain',                         'Pietrain', 'Porcino'),
('poland_china',                     'Poland China', 'Porcino'),
('spot',                             'Spot', 'Porcino'),
('yorkshire',                        'Yorkshire', 'Porcino'),

-- ── REPTIL ─────────────────────────────────────────────────────────────────
('boa_constrictor',                  'Boa Constrictor', 'Reptil'),
('dragon_barbudo',                   'Dragón Barbudo', 'Reptil'),
('gecko_leopardo',                   'Gecko Leopardo', 'Reptil'),
('iguana_verde',                     'Iguana Verde', 'Reptil'),
('piton_real',                       'Pitón Real', 'Reptil'),
('serpiente_del_maiz',               'Serpiente del Maíz', 'Reptil'),
('tortuga_morrocoy',                 'Tortuga Morrocoy', 'Reptil'),
('tortuga_orejas_rojas',             'Tortuga Orejas Rojas', 'Reptil'),

-- ── ROEDOR ─────────────────────────────────────────────────────────────────
('abisinio',                         'Abisinio', 'Roedor'),
('americano',                        'Americano', 'Roedor'),
('campbell',                         'Campbell', 'Roedor'),
('chino',                            'Chino', 'Roedor'),
('coronet',                          'Coronet', 'Roedor'),
('peruano',                          'Peruano', 'Roedor'),
('roborovski',                       'Roborovski', 'Roedor'),
('ruso',                             'Ruso', 'Roedor'),
('silkie',                           'Silkie', 'Roedor'),
('sirio',                            'Sirio', 'Roedor'),
('teddy',                            'Teddy', 'Roedor'),

-- ── SUGAR GLIDER ───────────────────────────────────────────────────────────
('sugar_glider',                     'Sugar Glider', 'Sugar Glider')

ON CONFLICT (breed_key, species) DO UPDATE SET
    name      = EXCLUDED.name,
    is_active = true;
