"""Detectores de intención por texto (texto → bool), por tema (Paso 3.4).

Superficie de import idéntica al detectors.py original: todo se re-exporta acá.
"""
from app.detectors.basico import (  # noqa: F401
    _AFFIRMATIVE_TOKENS,
    _CONTINUE_TOKENS,
    _FAREWELL_TOKENS,
    _GREETING_TOKENS,
    _NEGATIVE_TOKENS,
    _OTHER_CHOICE_TOKENS,
    _RESULTS_CHOICE_TOKENS,
    _confirms_new_client,
    _explicitly_says_new_client,
    _is_affirmative_text,
    _is_farewell,
    _is_greeting_only,
    _is_negative_text,
    _is_other_choice,
    _is_results_choice,
)
from app.detectors.perfil import (  # noqa: F401
    _AMBIGUOUS_PROFILE_TOKENS,
    _ARMED_PROFILE_TOKENS,
    _CLOSE_PROFILE_PHRASES,
    _CLOSE_PROFILE_TOKENS,
    _PROFILE_CONFIRM_TOKENS,
    _PROFILE_CUSTOMIZE_TOKENS,
    _asks_for_armed_profiles,
    _is_ambiguous_profile_change,
    _is_profile_confirmation,
    _is_profile_customization_request,
    _wants_to_close_custom_profile,
)
from app.detectors.direccion import (  # noqa: F401
    _ADDRESS_CONFIRM_TOKENS,
    _NO_OWNER_PHRASES,
    _NO_OWNER_TOKENS,
    _confirms_address,
    _rejects_address,
    _says_no_owner,
)
from app.detectors.orden import (  # noqa: F401
    _CONFIRM_ORDER_TOKENS,
    _CORRECTION_TOKENS,
    _HANDOFF_ACCEPT_TOKENS,
    _OPTION_CORRECTION_TOKENS,
    _OPTION_WORDS,
    _ORDER_REQUEST_TOKENS,
    _RECONSIDER_HINT_TOKENS,
    _accepts_handoff_offer,
    _confirms_order_now,
    _expresses_order_request,
    _is_correction_request,
    _is_order_confirmation,
    _wants_to_reconsider_option,
)
from app.detectors.cliente import (  # noqa: F401
    _BRANCH_NEW_SIGNAL_TOKENS,
    _BRANCH_NOUN_TOKENS,
    _CLIENT_CHANGE_SIGNAL_TOKENS,
    _CLIENT_NOUN_TOKENS,
    _NON_IDENTIFIER_TOKENS,
    _REJECT_ALL_MATCH_TOKENS,
    _asks_for_client_identity,
    _asks_if_new_client,
    _claims_unregistered_client,
    _is_no_identifier_text,
    _looks_like_bare_client_name,
    _rejects_match_options,
    _wants_new_branch,
    _wants_to_change_client,
)
from app.detectors.orden import (  # noqa: F401
    _SAME_AS_PHRASES,
    _SAME_AS_PREVIOUS_TOKENS,
    _is_same_as_previous,
)
from app.detectors.analisis import (  # noqa: F401
    _ACTION_STOPWORDS,
    _ANALYSIS_ADD_REMOVE_TOKENS,
    _ANALYSIS_CHANGE_SIGNAL_TOKENS,
    _ANALYSIS_NOUN_TOKENS,
    _DOESNT_KNOW_PHRASES,
    _EXAM_ITEM_SEPARATOR,
    _PARTIAL_KEEP_MARKERS,
    _PRICE_STOPWORDS,
    _PROCEED_TO_PAYMENT_PHRASES,
    _PROCEED_TO_PAYMENT_TOKENS,
    _PROFILE_DETAIL_TOKENS,
    _PROFILE_SPECIFIC_SUFFIXES,
    _RECOMMENDATION_TOKENS,
    _REMOVE_TOKENS,
    _detect_which_field_is_being_asked,
    _doesnt_know_what_to_ask,
    _is_generic_blood_analysis,
    _is_profile_detail_question,
    _last_bot_message,
    _looks_like_catalog_profile,
    _looks_like_specific_profile_query,
    _named_analysis_terms,
    _payment_method_from_text,
    _profile_codes_from_text,
    _split_multiple_exam_items,
    _wants_partial_analysis_change,
    _wants_profile_recommendation,
    _wants_to_change_analysis,
    _wants_to_proceed_to_payment,
)
from app.detectors.analisis import (  # noqa: F401
    _PRICE_QUESTION_TOKENS,
    _TOTAL_QUESTION_TOKENS,
)
